### PR TITLE
Misc. typos fixes

### PR DESCRIPTION
**Pull request by luzpaz**
Found via downstream VCVRack and using`codespell`

### CODE REVIEW

**Comment by memononen** [comment]
I merged the earlier PR which corrected the readme typo. The stb_* files are external libraries. I don't want those files to deviate from the official releases, I will only merge them fully from time to time.

**Comment by luzpaz** [comment]
@memononen what repo can the stb_* files be upstreamed to ?

**Comment by memononen** [comment]
You can find them here: https://github.com/nothings/stb

**Comment by luzpaz** [comment]
Submitted fixes upstream. Closing PR. Thanks.

**Pull request closed without merging**
